-- 171. The Report

SELECT
    CASE
        WHEN G.GRADE >= 8 THEN S.NAME
        ELSE NULL
        END NAME,
    G.GRADE, S.MARKS
FROM STUDENTS S JOIN GRADES G ON S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
WHERE
    G.GRADE >= 8 OR G.GRADE < 8
ORDER BY
    G.grade DESC,
    CASE
        WHEN G.GRADE >= 8 THEN S.NAME
        ELSE S.MARKS
        END;