-- 15. NULL 처리하기

SELECT ANIMAL_TYPE,
        IF (NAME IS NULL, "No name", NAME) NAME,
        SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID


SELECT ANIMAL_TYPE, 
        IFNULL(NAME, 'No name') NAME, 
        SEX_UPON_INTAKE 
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID;
