-- 137. Weather Observation Station 5

SELECT CITY AS city_name, LENGTH(CITY) AS city_length
FROM STATION
WHERE CITY = (
    SELECT CITY
    FROM STATION
    ORDER BY LENGTH(CITY) ASC, CITY ASC
    LIMIT 1
    )
   OR CITY = (
SELECT CITY
FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY ASC
    LIMIT 1
    );