-- 20. 가격이 제일 비싼 식품의 정보 출력하기

SELECT PRODUCT_ID,
        PRODUCT_NAME,
        PRODUCT_CD,
        CATEGORY,
        PRICE
FROM FOOD_PRODUCT 
ORDER BY 5 DESC
LIMIT 1



SELECT *
FROM FOOD_PRODUCT 
WHERE PRICE = (SELECT MAX(PRICE) 
               FROM FOOD_PRODUCT)
