-- 24. 카테고리 별 상품 개수 구하기

SELECT SUBSTR(PRODUCT_CODE, 1, 2) CATEGORY,
        COUNT(PRODUCT_ID) PRODUCTS
FROM PRODUCT 
GROUP BY 1
ORDER BY 1



SELECT SUBSTR(PRODUCT_CODE, 1, 2) CATEGORY,
        COUNT(PRODUCT_ID) PRODUCTS
FROM PRODUCT 
GROUP BY CATEGORY
ORDER BY CATEGORY
