-- 33. 상품 별 오프라인 매출 구하기

SELECT P.PRODUCT_CODE,
        SUM(O_SALE.SALES_AMOUNT)*P.PRICE SALES
FROM PRODUCT P INNER JOIN OFFLINE_SALE O_SALE ON P.PRODUCT_ID = O_SALE.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY 2 DESC, 1
