-- 36. 보호소에서 중성화한 동물

SELECT A_INS.ANIMAL_ID, A_INS.ANIMAL_TYPE, A_INS.NAME
FROM ANIMAL_INS A_INS INNER JOIN ANIMAL_OUTS A_OUTS ON A_INS.ANIMAL_ID = A_OUTS.ANIMAL_ID
WHERE A_INS.SEX_UPON_INTAKE LIKE '%Intact%' AND ( A_OUTS.SEX_UPON_OUTCOME LIKE '%Neutered%' OR A_OUTS.SEX_UPON_OUTCOME LIKE '%Spayed%' )
ORDER BY 1 
