-- 46. 대여 기록이 존재하는 자동차 리스트 구하기

SELECT DISTINCT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY ON CAR.CAR_ID = HISTORY.CAR_ID
WHERE MONTH(HISTORY.START_DATE) = '10' AND CAR.CAR_TYPE LIKE '%세단%'
ORDER BY 1 DESC
