-- 67. 주문량이 많은 아이스크림들 조회하기


SELECT HALF.FLAVOR
FROM FIRST_HALF HALF JOIN JULY JULY ON HALF.FLAVOR = JULY.FLAVOR
GROUP BY HALF.FLAVOR
HAVING SUM(HALF.TOTAL_ORDER + JULY.TOTAL_ORDER)
ORDER BY SUM(HALF.TOTAL_ORDER + JULY.TOTAL_ORDER) DESC
LIMIT 3