-- 60. 년, 월, 성별 별 상품 구매 회원 수 구하기

SELECT YEAR(O.SALES_DATE) 'YEAR', MONTH(O.SALES_DATE) 'MONTH', U.GENDER 'GENDER', COUNT(DISTINCT O.USER_ID) 'USERS'
FROM USER_INFO U JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY 1, 2, 3