-- 68. 저자 별 카테고리 별 매출액 집계하기

SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(SALES.SALES*BOOK.PRICE) 'TOTAL_SALES'
FROM BOOK BOOK
JOIN AUTHOR AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
JOIN BOOK_SALES SALES ON BOOK.BOOK_ID = SALES.BOOK_ID
WHERE YEAR(SALES.SALES_DATE) = '2022' AND MONTH(SALES.SALES_DATE) = '01'
GROUP BY AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY DESC